name: simple_dart_web_widgets
description: Simple dart web widgets.
version: 0.0.1
publish_to: none

environment:
  sdk: '^2.13.4'

#dependencies:

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers:
